//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shane.Church.StirlingMoney.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shane.Church.StirlingMoney.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name is required..
        /// </summary>
        public static string AccountNameRequiredError {
            get {
                return ResourceManager.GetString("AccountNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is required..
        /// </summary>
        public static string AccountRequiredError {
            get {
                return ResourceManager.GetString("AccountRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add account.
        /// </summary>
        public static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add budget.
        /// </summary>
        public static string AddBudgetTitle {
            get {
                return ResourceManager.GetString("AddBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add goal.
        /// </summary>
        public static string AddGoalTitle {
            get {
                return ResourceManager.GetString("AddGoalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remaining.
        /// </summary>
        public static string AmountRemaining {
            get {
                return ResourceManager.GetString("AmountRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Expenses.
        /// </summary>
        public static string BudgetAllExpensesLabel {
            get {
                return ResourceManager.GetString("BudgetAllExpensesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required and must be greater than 0..
        /// </summary>
        public static string BudgetAmountRequiredError {
            get {
                return ResourceManager.GetString("BudgetAmountRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string BudgetCustom {
            get {
                return ResourceManager.GetString("BudgetCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be after Start Date..
        /// </summary>
        public static string BudgetEndDateRangeError {
            get {
                return ResourceManager.GetString("BudgetEndDateRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is required for Custom budget periods..
        /// </summary>
        public static string BudgetEndDateRequiredError {
            get {
                return ResourceManager.GetString("BudgetEndDateRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string BudgetMonthly {
            get {
                return ResourceManager.GetString("BudgetMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string BudgetNameRequiredError {
            get {
                return ResourceManager.GetString("BudgetNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string BudgetWeekly {
            get {
                return ResourceManager.GetString("BudgetWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string BudgetYearly {
            get {
                return ResourceManager.GetString("BudgetYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by category.
        /// </summary>
        public static string CategoryChartTypeByCategory {
            get {
                return ResourceManager.GetString("CategoryChartTypeByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string CategoryChartTypeHistory {
            get {
                return ResourceManager.GetString("CategoryChartTypeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name is required..
        /// </summary>
        public static string CategoryNameRequiredError {
            get {
                return ResourceManager.GetString("CategoryNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        public static string CheckTitle {
            get {
                return ResourceManager.GetString("CheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day overdue.
        /// </summary>
        public static string DayOverdue {
            get {
                return ResourceManager.GetString("DayOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day remaining.
        /// </summary>
        public static string DayRemaining {
            get {
                return ResourceManager.GetString("DayRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days overdue.
        /// </summary>
        public static string DaysOverdue {
            get {
                return ResourceManager.GetString("DaysOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days remaining.
        /// </summary>
        public static string DaysRemaining {
            get {
                return ResourceManager.GetString("DaysRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deposit.
        /// </summary>
        public static string DepositTitle {
            get {
                return ResourceManager.GetString("DepositTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit account.
        /// </summary>
        public static string EditAccountTitle {
            get {
                return ResourceManager.GetString("EditAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit budget.
        /// </summary>
        public static string EditBudgetTitle {
            get {
                return ResourceManager.GetString("EditBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit goal.
        /// </summary>
        public static string EditGoalTitle {
            get {
                return ResourceManager.GetString("EditGoalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is required..
        /// </summary>
        public static string GoalAccountRequiredError {
            get {
                return ResourceManager.GetString("GoalAccountRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to achieved!.
        /// </summary>
        public static string GoalAchieved {
            get {
                return ResourceManager.GetString("GoalAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than the current balance of the selected account..
        /// </summary>
        public static string GoalAmountError {
            get {
                return ResourceManager.GetString("GoalAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date must be after today..
        /// </summary>
        public static string GoalDateError {
            get {
                return ResourceManager.GetString("GoalDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string GoalNameRequiredError {
            get {
                return ResourceManager.GetString("GoalNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required..
        /// </summary>
        public static string LocationRequiredError {
            get {
                return ResourceManager.GetString("LocationRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no category).
        /// </summary>
        public static string NoCategoryLabel {
            get {
                return ResourceManager.GetString("NoCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherLabel {
            get {
                return ResourceManager.GetString("OtherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alphabetically.
        /// </summary>
        public static string SettingsAccountSortAlpha {
            get {
                return ResourceManager.GetString("SettingsAccountSortAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to most frequently used.
        /// </summary>
        public static string SettingsAccountSortMostFrequentlyUsed {
            get {
                return ResourceManager.GetString("SettingsAccountSortMostFrequentlyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is required..
        /// </summary>
        public static string SettingsConfirmPasswordRequiredError {
            get {
                return ResourceManager.GetString("SettingsConfirmPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must match Confirm Password..
        /// </summary>
        public static string SettingsPasswordMismatchError {
            get {
                return ResourceManager.GetString("SettingsPasswordMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string SettingsPasswordRequiredError {
            get {
                return ResourceManager.GetString("SettingsPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer from.
        /// </summary>
        public static string TransferFromComparisonString {
            get {
                return ResourceManager.GetString("TransferFromComparisonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer from {0}.
        /// </summary>
        public static string TransferFromLocation {
            get {
                return ResourceManager.GetString("TransferFromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer.
        /// </summary>
        public static string TransferTitle {
            get {
                return ResourceManager.GetString("TransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to.
        /// </summary>
        public static string TransferToComparisonString {
            get {
                return ResourceManager.GetString("TransferToComparisonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to {0}.
        /// </summary>
        public static string TransferToLocation {
            get {
                return ResourceManager.GetString("TransferToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Click the buy button bellow in order to purchase the full version..
        /// </summary>
        public static string TrialMessagePurchaseText {
            get {
                return ResourceManager.GetString("TrialMessagePurchaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string UnknownTitle {
            get {
                return ResourceManager.GetString("UnknownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin from start.
        /// </summary>
        public static string UnpinFromStart {
            get {
                return ResourceManager.GetString("UnpinFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to withdrawal.
        /// </summary>
        public static string WithdrawalTitle {
            get {
                return ResourceManager.GetString("WithdrawalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
