//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shane.Church.StirlingMoney.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shane.Church.StirlingMoney.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other apps by Shane Church.
        /// </summary>
        public static string AboutOtherAppsLabel {
            get {
                return ResourceManager.GetString("AboutOtherAppsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this app.
        /// </summary>
        public static string AboutReviewLabel {
            get {
                return ResourceManager.GetString("AboutReviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account image.
        /// </summary>
        public static string AccountImageLabel {
            get {
                return ResourceManager.GetString("AccountImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account name.
        /// </summary>
        public static string AccountNameLabel {
            get {
                return ResourceManager.GetString("AccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name is required..
        /// </summary>
        public static string AccountNameRequiredError {
            get {
                return ResourceManager.GetString("AccountNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is required..
        /// </summary>
        public static string AccountRequiredError {
            get {
                return ResourceManager.GetString("AccountRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string ActualChartLabel {
            get {
                return ResourceManager.GetString("ActualChartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an account to get started.
        /// </summary>
        public static string AddAccountPrompt {
            get {
                return ResourceManager.GetString("AddAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Budget.
        /// </summary>
        public static string AddBudgetTitle {
            get {
                return ResourceManager.GetString("AddBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategoryTitle {
            get {
                return ResourceManager.GetString("AddCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Goal.
        /// </summary>
        public static string AddGoalTitle {
            get {
                return ResourceManager.GetString("AddGoalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task synchronizes Stirling Money data with any shared users and updates the live tiles..
        /// </summary>
        public static string AgentDescription {
            get {
                return ResourceManager.GetString("AgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents for this application have been disabled by the user..
        /// </summary>
        public static string AgentsDisabledByUserError {
            get {
                return ResourceManager.GetString("AgentsDisabledByUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device does not support background agents, so this feature will be disabled..
        /// </summary>
        public static string AgentsNotSupportedError {
            get {
                return ResourceManager.GetString("AgentsNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountChartLabel {
            get {
                return ResourceManager.GetString("AmountChartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remaining.
        /// </summary>
        public static string AmountRemaining {
            get {
                return ResourceManager.GetString("AmountRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarAdd {
            get {
                return ResourceManager.GetString("AppBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add account.
        /// </summary>
        public static string AppBarAddAccount {
            get {
                return ResourceManager.GetString("AppBarAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup.
        /// </summary>
        public static string AppBarBackup {
            get {
                return ResourceManager.GetString("AppBarBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories.
        /// </summary>
        public static string AppBarCategories {
            get {
                return ResourceManager.GetString("AppBarCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deposit.
        /// </summary>
        public static string AppBarDeposit {
            get {
                return ResourceManager.GetString("AppBarDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review this app.
        /// </summary>
        public static string AppBarMenuItemReview {
            get {
                return ResourceManager.GetString("AppBarMenuItemReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reports.
        /// </summary>
        public static string AppBarReports {
            get {
                return ResourceManager.GetString("AppBarReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string AppBarSync {
            get {
                return ResourceManager.GetString("AppBarSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer.
        /// </summary>
        public static string AppBarTransfer {
            get {
                return ResourceManager.GetString("AppBarTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to withdraw.
        /// </summary>
        public static string AppBarWithdraw {
            get {
                return ResourceManager.GetString("AppBarWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write check.
        /// </summary>
        public static string AppBarWriteCheck {
            get {
                return ResourceManager.GetString("AppBarWriteCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Shane Church 2013.
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A financial organizer for Windows Phone.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirling Money.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial of this application has expired. Do you want to purchase the application now? If you choose Yes - you will be redirected to the marketplace..
        /// </summary>
        public static string AppTrialEnd_MessageBox_Content {
            get {
                return ResourceManager.GetString("AppTrialEnd_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this reminder again.
        /// </summary>
        public static string AppTrialEnd_MessageBox_SkipFurtherRemindersMessage {
            get {
                return ResourceManager.GetString("AppTrialEnd_MessageBox_SkipFurtherRemindersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Expired.
        /// </summary>
        public static string AppTrialEnd_MessageBox_Title {
            get {
                return ResourceManager.GetString("AppTrialEnd_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the ad-supported trial version of this application. Do you want to purchase the application now to remove the ads? If you choose Yes - you will be redirected to the marketplace..
        /// </summary>
        public static string AppTrialReminder_MessageBox_Content {
            get {
                return ResourceManager.GetString("AppTrialReminder_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this reminder again.
        /// </summary>
        public static string AppTrialReminder_MessageBox_SkipFurtherRemindersMessage {
            get {
                return ResourceManager.GetString("AppTrialReminder_MessageBox_SkipFurtherRemindersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Reminder.
        /// </summary>
        public static string AppTrialReminder_MessageBox_Title {
            get {
                return ResourceManager.GetString("AppTrialReminder_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirling Money can share data between authorized users so you and your family are always up to date on where your accounts stand. Enter the Microsoft Account email address of the user or users you would like to synchronize and share your data with below..
        /// </summary>
        public static string AuthorizedUsersDescription {
            get {
                return ResourceManager.GetString("AuthorizedUsersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Users.
        /// </summary>
        public static string AuthorizedUsersTitle {
            get {
                return ResourceManager.GetString("AuthorizedUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup.
        /// </summary>
        public static string BackupButton {
            get {
                return ResourceManager.GetString("BackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error backing up database: {0}.
        /// </summary>
        public static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap backup to save your data to the Stirling Money folder in OneDrive. This will overwrite any existing backup.
        ///
        ///Tap restore to overwrite your local data with your backup from OneDrive..
        /// </summary>
        public static string BackupInstructions {
            get {
                return ResourceManager.GetString("BackupInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Signed In..
        /// </summary>
        public static string BackupNotSignedIn {
            get {
                return ResourceManager.GetString("BackupNotSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting with OneDrive: {0}.
        /// </summary>
        public static string BackupOneDriveError {
            get {
                return ResourceManager.GetString("BackupOneDriveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred restoring database..
        /// </summary>
        public static string BackupRestoreError {
            get {
                return ResourceManager.GetString("BackupRestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error restoring database: {0}.
        /// </summary>
        public static string BackupRestoreException {
            get {
                return ResourceManager.GetString("BackupRestoreException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find an existing backup file to restore..
        /// </summary>
        public static string BackupRestoreNoBackupError {
            get {
                return ResourceManager.GetString("BackupRestoreNoBackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database restored successfully..
        /// </summary>
        public static string BackupRestoreSuccess {
            get {
                return ResourceManager.GetString("BackupRestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed In..
        /// </summary>
        public static string BackupSignedIn {
            get {
                return ResourceManager.GetString("BackupSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backed up successfully..
        /// </summary>
        public static string BackupSuccess {
            get {
                return ResourceManager.GetString("BackupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupTitle {
            get {
                return ResourceManager.GetString("BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Expenses.
        /// </summary>
        public static string BudgetAllExpensesLabel {
            get {
                return ResourceManager.GetString("BudgetAllExpensesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.
        /// </summary>
        public static string BudgetAmountLabel {
            get {
                return ResourceManager.GetString("BudgetAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required and must be greater than 0..
        /// </summary>
        public static string BudgetAmountRequiredError {
            get {
                return ResourceManager.GetString("BudgetAmountRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string BudgetChartLabel {
            get {
                return ResourceManager.GetString("BudgetChartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string BudgetCustom {
            get {
                return ResourceManager.GetString("BudgetCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end date.
        /// </summary>
        public static string BudgetEndDateLabel {
            get {
                return ResourceManager.GetString("BudgetEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be after Start Date..
        /// </summary>
        public static string BudgetEndDateRangeError {
            get {
                return ResourceManager.GetString("BudgetEndDateRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is required for Custom budget periods..
        /// </summary>
        public static string BudgetEndDateRequiredError {
            get {
                return ResourceManager.GetString("BudgetEndDateRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string BudgetMonthly {
            get {
                return ResourceManager.GetString("BudgetMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string BudgetNameLabel {
            get {
                return ResourceManager.GetString("BudgetNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string BudgetNameRequiredError {
            get {
                return ResourceManager.GetString("BudgetNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to period.
        /// </summary>
        public static string BudgetPeriodLabel {
            get {
                return ResourceManager.GetString("BudgetPeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start date.
        /// </summary>
        public static string BudgetStartDateLabel {
            get {
                return ResourceManager.GetString("BudgetStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgets.
        /// </summary>
        public static string BudgetsTitle {
            get {
                return ResourceManager.GetString("BudgetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget.
        /// </summary>
        public static string BudgetTitle {
            get {
                return ResourceManager.GetString("BudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string BudgetTypeLabel {
            get {
                return ResourceManager.GetString("BudgetTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string BudgetWeekly {
            get {
                return ResourceManager.GetString("BudgetWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string BudgetYearly {
            get {
                return ResourceManager.GetString("BudgetYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobile.
        /// </summary>
        public static string CategoryAutomobile {
            get {
                return ResourceManager.GetString("CategoryAutomobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string CategoryBills {
            get {
                return ResourceManager.GetString("CategoryBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string CategoryBusiness {
            get {
                return ResourceManager.GetString("CategoryBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity.
        /// </summary>
        public static string CategoryCharity {
            get {
                return ResourceManager.GetString("CategoryCharity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by category.
        /// </summary>
        public static string CategoryChartTypeByCategory {
            get {
                return ResourceManager.GetString("CategoryChartTypeByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string CategoryChartTypeHistory {
            get {
                return ResourceManager.GetString("CategoryChartTypeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        public static string CategoryClothing {
            get {
                return ResourceManager.GetString("CategoryClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string CategoryDeposit {
            get {
                return ResourceManager.GetString("CategoryDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string CategoryEntertainment {
            get {
                return ResourceManager.GetString("CategoryEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string CategoryFood {
            get {
                return ResourceManager.GetString("CategoryFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string CategoryHealth {
            get {
                return ResourceManager.GetString("CategoryHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string CategoryHome {
            get {
                return ResourceManager.GetString("CategoryHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string CategoryMiscellaneous {
            get {
                return ResourceManager.GetString("CategoryMiscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category name.
        /// </summary>
        public static string CategoryNameLabel {
            get {
                return ResourceManager.GetString("CategoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name is required..
        /// </summary>
        public static string CategoryNameRequiredError {
            get {
                return ResourceManager.GetString("CategoryNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string CategoryUtilities {
            get {
                return ResourceManager.GetString("CategoryUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        public static string CategoryVacation {
            get {
                return ResourceManager.GetString("CategoryVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chart types.
        /// </summary>
        public static string ChartTypesTitle {
            get {
                return ResourceManager.GetString("ChartTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string CheckTitle {
            get {
                return ResourceManager.GetString("CheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credit limit.
        /// </summary>
        public static string CreditLimitLabel {
            get {
                return ResourceManager.GetString("CreditLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string DateRangeLabel {
            get {
                return ResourceManager.GetString("DateRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day overdue.
        /// </summary>
        public static string DayOverdue {
            get {
                return ResourceManager.GetString("DayOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day remaining.
        /// </summary>
        public static string DayRemaining {
            get {
                return ResourceManager.GetString("DayRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days overdue.
        /// </summary>
        public static string DaysOverdue {
            get {
                return ResourceManager.GetString("DaysOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days remaining.
        /// </summary>
        public static string DaysRemaining {
            get {
                return ResourceManager.GetString("DaysRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string DeleteAccountTitle {
            get {
                return ResourceManager.GetString("DeleteAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account, all of its transactions, and all associated goals?.
        /// </summary>
        public static string DeleteAccountWarning {
            get {
                return ResourceManager.GetString("DeleteAccountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Budget.
        /// </summary>
        public static string DeleteBudgetTitle {
            get {
                return ResourceManager.GetString("DeleteBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this budget?.
        /// </summary>
        public static string DeleteBudgetWarning {
            get {
                return ResourceManager.GetString("DeleteBudgetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Goal.
        /// </summary>
        public static string DeleteGoalTitle {
            get {
                return ResourceManager.GetString("DeleteGoalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this goal?.
        /// </summary>
        public static string DeleteGoalWarning {
            get {
                return ResourceManager.GetString("DeleteGoalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteMenuItem {
            get {
                return ResourceManager.GetString("DeleteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Transaction.
        /// </summary>
        public static string DeleteTransactionTitle {
            get {
                return ResourceManager.GetString("DeleteTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this transaction?.
        /// </summary>
        public static string DeleteTransactionWarning {
            get {
                return ResourceManager.GetString("DeleteTransactionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string DepositTitle {
            get {
                return ResourceManager.GetString("DepositTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has encountered a problem. I am sorry for the inconvenience.
        ///
        ///I would appreciate your assistance by sending the prepared error report. This will help with resolving the problem faster..
        /// </summary>
        public static string Diagnostics_MessageBox_Content {
            get {
                return ResourceManager.GetString("Diagnostics_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        public static string Diagnostics_MessageBox_Title {
            get {
                return ResourceManager.GetString("Diagnostics_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloaded {0} of {1} bytes....
        /// </summary>
        public static string DownloadingProgressText {
            get {
                return ResourceManager.GetString("DownloadingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        public static string EditAccountTitle {
            get {
                return ResourceManager.GetString("EditAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Budget.
        /// </summary>
        public static string EditBudgetTitle {
            get {
                return ResourceManager.GetString("EditBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Goal.
        /// </summary>
        public static string EditGoalTitle {
            get {
                return ResourceManager.GetString("EditGoalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditMenuItem {
            get {
                return ResourceManager.GetString("EditMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your password.
        /// </summary>
        public static string EnterPasswordLabel {
            get {
                return ResourceManager.GetString("EnterPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string ExpensesChartLabel {
            get {
                return ResourceManager.GetString("ExpensesChartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I improve this application so that you would be willing to rate it 5 stars in the marketplace?.
        /// </summary>
        public static string FeedbackContent {
            get {
                return ResourceManager.GetString("FeedbackContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I make it better?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirling Money Error.
        /// </summary>
        public static string GeneralErrorCaption {
            get {
                return ResourceManager.GetString("GeneralErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string GiveFeedbackButton {
            get {
                return ResourceManager.GetString("GiveFeedbackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string GoalAccountLabel {
            get {
                return ResourceManager.GetString("GoalAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is required..
        /// </summary>
        public static string GoalAccountRequiredError {
            get {
                return ResourceManager.GetString("GoalAccountRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to achieved!.
        /// </summary>
        public static string GoalAchieved {
            get {
                return ResourceManager.GetString("GoalAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than the current balance of the selected account..
        /// </summary>
        public static string GoalAmountError {
            get {
                return ResourceManager.GetString("GoalAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.
        /// </summary>
        public static string GoalAmountLabel {
            get {
                return ResourceManager.GetString("GoalAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date must be after {0:d}.
        /// </summary>
        public static string GoalDateComparisonError {
            get {
                return ResourceManager.GetString("GoalDateComparisonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date must be after today..
        /// </summary>
        public static string GoalDateError {
            get {
                return ResourceManager.GetString("GoalDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string GoalNameLabel {
            get {
                return ResourceManager.GetString("GoalNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string GoalNameRequiredError {
            get {
                return ResourceManager.GetString("GoalNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select account.
        /// </summary>
        public static string GoalSelectAccountLabel {
            get {
                return ResourceManager.GetString("GoalSelectAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start date.
        /// </summary>
        public static string GoalStartDateLabel {
            get {
                return ResourceManager.GetString("GoalStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string GoalsTitle {
            get {
                return ResourceManager.GetString("GoalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target date.
        /// </summary>
        public static string GoalTargetDateLabel {
            get {
                return ResourceManager.GetString("GoalTargetDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string IncomeChartLabel {
            get {
                return ResourceManager.GetString("IncomeChartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initial balance.
        /// </summary>
        public static string InitialBalanceLabel {
            get {
                return ResourceManager.GetString("InitialBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        public static string InvalidPasswordExitButton {
            get {
                return ResourceManager.GetString("InvalidPasswordExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        public static string InvalidPasswordRetryButton {
            get {
                return ResourceManager.GetString("InvalidPasswordRetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Invalid Values.
        /// </summary>
        public static string InvalidValuesTitle {
            get {
                return ResourceManager.GetString("InvalidValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credit card.
        /// </summary>
        public static string IsCreditCardLabel {
            get {
                return ResourceManager.GetString("IsCreditCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required..
        /// </summary>
        public static string LocationRequiredError {
            get {
                return ResourceManager.GetString("LocationRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string MBCancelText {
            get {
                return ResourceManager.GetString("MBCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string MBNoText {
            get {
                return ResourceManager.GetString("MBNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string MBOkText {
            get {
                return ResourceManager.GetString("MBOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string MBYesText {
            get {
                return ResourceManager.GetString("MBYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Income.
        /// </summary>
        public static string NetIncomeTitle {
            get {
                return ResourceManager.GetString("NetIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add authorized user account.
        /// </summary>
        public static string NewAuthorizedUser {
            get {
                return ResourceManager.GetString("NewAuthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Authorized Users.
        /// </summary>
        public static string NoAuthorizedUsers {
            get {
                return ResourceManager.GetString("NoAuthorizedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no category).
        /// </summary>
        public static string NoCategoryLabel {
            get {
                return ResourceManager.GetString("NoCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoDataLabel {
            get {
                return ResourceManager.GetString("NoDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string NoThanksButton {
            get {
                return ResourceManager.GetString("NoThanksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherLabel {
            get {
                return ResourceManager.GetString("OtherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validating....
        /// </summary>
        public static string PasswordValidatingText {
            get {
                return ResourceManager.GetString("PasswordValidatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid password.
        /// </summary>
        public static string PasswordValidationError {
            get {
                return ResourceManager.GetString("PasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string ProgressBarDownloadingText {
            get {
                return ResourceManager.GetString("ProgressBarDownloadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing....
        /// </summary>
        public static string ProgressBarSyncText {
            get {
                return ResourceManager.GetString("ProgressBarSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string ProgressBarText {
            get {
                return ResourceManager.GetString("ProgressBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating database.
        /// </summary>
        public static string ProgressBarUpdatingText {
            get {
                return ResourceManager.GetString("ProgressBarUpdatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string ProgressBarUploadingText {
            get {
                return ResourceManager.GetString("ProgressBarUploadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy full version.
        /// </summary>
        public static string PurchaseFullVersionButton {
            get {
                return ResourceManager.GetString("PurchaseFullVersionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would love to hear from you! If you like the app, please rate it on the marketplace and share your feedback..
        /// </summary>
        public static string RateReminder_MessageBox_Content {
            get {
                return ResourceManager.GetString("RateReminder_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this reminder again.
        /// </summary>
        public static string RateReminder_MessageBox_SkipFurtherRemindersMessage {
            get {
                return ResourceManager.GetString("RateReminder_MessageBox_SkipFurtherRemindersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the app.
        /// </summary>
        public static string RateReminder_MessageBox_Title {
            get {
                return ResourceManager.GetString("RateReminder_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirling Money - Reports.
        /// </summary>
        public static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore.
        /// </summary>
        public static string RestoreButton {
            get {
                return ResourceManager.GetString("RestoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select date.
        /// </summary>
        public static string SelectDateText {
            get {
                return ResourceManager.GetString("SelectDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alphabetically.
        /// </summary>
        public static string SettingsAccountSortAlpha {
            get {
                return ResourceManager.GetString("SettingsAccountSortAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort account list by.
        /// </summary>
        public static string SettingsAccountSortLabel {
            get {
                return ResourceManager.GetString("SettingsAccountSortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to most frequently used.
        /// </summary>
        public static string SettingsAccountSortMostFrequentlyUsed {
            get {
                return ResourceManager.GetString("SettingsAccountSortMostFrequentlyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm password.
        /// </summary>
        public static string SettingsConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("SettingsConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is required..
        /// </summary>
        public static string SettingsConfirmPasswordRequiredError {
            get {
                return ResourceManager.GetString("SettingsConfirmPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string SettingsPasswordLabel {
            get {
                return ResourceManager.GetString("SettingsPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must match Confirm Password..
        /// </summary>
        public static string SettingsPasswordMismatchError {
            get {
                return ResourceManager.GetString("SettingsPasswordMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string SettingsPasswordRequiredError {
            get {
                return ResourceManager.GetString("SettingsPasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use password.
        /// </summary>
        public static string SettingsUsePasswordLabel {
            get {
                return ResourceManager.GetString("SettingsUsePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance: {0}.
        /// </summary>
        public static string StartTileBalance {
            get {
                return ResourceManager.GetString("StartTileBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable synchronization.
        /// </summary>
        public static string SynchronizationEnableLabel {
            get {
                return ResourceManager.GetString("SynchronizationEnableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirling Money can be synchronized and backed up to Windows Azure. Additionally, individual accounts may be shared with other users like your spouse.
        ///
        ///I take your security very seriously and all data is transmitted securely over HTTPS and is anonymously secured using your Microsoft account credentials. Stirling Money does not store any account specific like account or routing numbers or personally identifiable information like your name or login information. If you have further questions, please contact m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SynchronizationExplanation {
            get {
                return ResourceManager.GetString("SynchronizationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirling Money Synchronization Question or Concern.
        /// </summary>
        public static string SynchronizationFeedbackEmailSubject {
            get {
                return ResourceManager.GetString("SynchronizationFeedbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to questions or concerns.
        /// </summary>
        public static string SynchronizationFeedbackLink {
            get {
                return ResourceManager.GetString("SynchronizationFeedbackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        public static string SynchronizationTitle {
            get {
                return ResourceManager.GetString("SynchronizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to sync..
        /// </summary>
        public static string SyncLoginError {
            get {
                return ResourceManager.GetString("SyncLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synchronize on startup.
        /// </summary>
        public static string SyncOnStartupLabel {
            get {
                return ResourceManager.GetString("SyncOnStartupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sync at this time. Please try again later..
        /// </summary>
        public static string SyncUnknownError {
            get {
                return ResourceManager.GetString("SyncUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to technical support/feedback email.
        /// </summary>
        public static string TechnicalSupportEmailLabel {
            get {
                return ResourceManager.GetString("TechnicalSupportEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirling Money Feedback.
        /// </summary>
        public static string TechnicalSupportEmailSubject {
            get {
                return ResourceManager.GetString("TechnicalSupportEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server unavailable.
        /// </summary>
        public static string ToastServerUnavailable {
            get {
                return ResourceManager.GetString("ToastServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sync Error.
        /// </summary>
        public static string ToastSyncError {
            get {
                return ResourceManager.GetString("ToastSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many background agents have been enabled. Please go to the settings application to disable other agents before enabling the Stirling Birthday agent..
        /// </summary>
        public static string TooManyAgentsError {
            get {
                return ResourceManager.GetString("TooManyAgentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total balance.
        /// </summary>
        public static string TotalBalanceLabel {
            get {
                return ResourceManager.GetString("TotalBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string TransactionAccountLabel {
            get {
                return ResourceManager.GetString("TransactionAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.
        /// </summary>
        public static string TransactionAmountLabel {
            get {
                return ResourceManager.GetString("TransactionAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string TransactionCategoryLabel {
            get {
                return ResourceManager.GetString("TransactionCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        public static string TransactionCheckNumberLabel {
            get {
                return ResourceManager.GetString("TransactionCheckNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string TransactionDateLabel {
            get {
                return ResourceManager.GetString("TransactionDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string TransactionLocationLabel {
            get {
                return ResourceManager.GetString("TransactionLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string TransactionNotesLabel {
            get {
                return ResourceManager.GetString("TransactionNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posted.
        /// </summary>
        public static string TransactionPostedLabel {
            get {
                return ResourceManager.GetString("TransactionPostedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available balance.
        /// </summary>
        public static string TransactionsAvailableBalanceLabel {
            get {
                return ResourceManager.GetString("TransactionsAvailableBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select account.
        /// </summary>
        public static string TransactionSelectAccountLabel {
            get {
                return ResourceManager.GetString("TransactionSelectAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string TransactionsLoadingTitle {
            get {
                return ResourceManager.GetString("TransactionsLoadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Transactions.
        /// </summary>
        public static string TransactionsNoData {
            get {
                return ResourceManager.GetString("TransactionsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posted balance.
        /// </summary>
        public static string TransactionsPostedBalanceLabel {
            get {
                return ResourceManager.GetString("TransactionsPostedBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer from.
        /// </summary>
        public static string TransferFromComparisonString {
            get {
                return ResourceManager.GetString("TransferFromComparisonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer from {0}.
        /// </summary>
        public static string TransferFromLocation {
            get {
                return ResourceManager.GetString("TransferFromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string TransferTitle {
            get {
                return ResourceManager.GetString("TransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to.
        /// </summary>
        public static string TransferToComparisonString {
            get {
                return ResourceManager.GetString("TransferToComparisonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to {0}.
        /// </summary>
        public static string TransferToLocation {
            get {
                return ResourceManager.GetString("TransferToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is only available in the full version..
        /// </summary>
        public static string TrialMessageGeneric {
            get {
                return ResourceManager.GetString("TrialMessageGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Click the buy button bellow in order to purchase the full version..
        /// </summary>
        public static string TrialMessagePurchaseText {
            get {
                return ResourceManager.GetString("TrialMessagePurchaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only ten (10) transactions per account are allowed in trial mode..
        /// </summary>
        public static string TrialMessageTenTransactions {
            get {
                return ResourceManager.GetString("TrialMessageTenTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only two (2) accounts are allowed in trial mode..
        /// </summary>
        public static string TrialMessageTwoAccounts {
            get {
                return ResourceManager.GetString("TrialMessageTwoAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} day(s) left..
        /// </summary>
        public static string TrialReminderPeriodMessage {
            get {
                return ResourceManager.GetString("TrialReminderPeriodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} time(s) left..
        /// </summary>
        public static string TrialReminderUsageCountMessage {
            get {
                return ResourceManager.GetString("TrialReminderUsageCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string TrialTitle {
            get {
                return ResourceManager.GetString("TrialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownTitle {
            get {
                return ResourceManager.GetString("UnknownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin from start.
        /// </summary>
        public static string UnpinFromStart {
            get {
                return ResourceManager.GetString("UnpinFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded {0} of {1} bytes....
        /// </summary>
        public static string UploadingProgressText {
            get {
                return ResourceManager.GetString("UploadingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal.
        /// </summary>
        public static string WithdrawalTitle {
            get {
                return ResourceManager.GetString("WithdrawalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the 30 day free trial of the synchronization services. Would you like to purchase the application to continue using the services beyond the trial? If you choose Yes - you will be redirected to the marketplace..
        /// </summary>
        public static string WP7SyncTrialReminder_Content {
            get {
                return ResourceManager.GetString("WP7SyncTrialReminder_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Reminder.
        /// </summary>
        public static string WP7SyncTrialReminder_Title {
            get {
                return ResourceManager.GetString("WP7SyncTrialReminder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your synchronization service triial has expired. Do you want to purchase the application now? If you choose Yes - you will be redirected to the marketplace..
        /// </summary>
        public static string WP7SyncTrialReminderExpired_Content {
            get {
                return ResourceManager.GetString("WP7SyncTrialReminderExpired_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Expired.
        /// </summary>
        public static string WP7SyncTrialReminderExpired_Title {
            get {
                return ResourceManager.GetString("WP7SyncTrialReminderExpired_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
