//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;

namespace Shane.Church.StirlingMoney.Data.Sync
{
    
    
    #region SyncService: Configuration and setup
    public class Server_SyncService : Microsoft.Synchronization.Services.SyncService<Server_OfflineEntities> {
        
        public static void InitializeService(Microsoft.Synchronization.Services.ISyncServiceConfiguration config) {
			config.ServerConnectionString = ConfigurationManager.ConnectionStrings["SyncServer"].ConnectionString;
			config.SetEnableScope("DefaultScope");
			config.SetDefaultSyncSerializationFormat(Microsoft.Synchronization.Services.SyncSerializationFormat.ODataJson);
			config.SetConflictResolutionPolicy(Microsoft.Synchronization.Services.ConflictResolutionPolicy.ServerWins);
						
			config.SetSyncObjectSchema("dbo");
			config.EnableDiagnosticPage = true;
			config.UseVerboseErrors = true;
        }
    }
    #endregion
}
