//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shane.Church.StirlingMoney.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shane.Church.StirlingMoney.Data.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobile.
        /// </summary>
        public static string CategoryAutomobile {
            get {
                return ResourceManager.GetString("CategoryAutomobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string CategoryBills {
            get {
                return ResourceManager.GetString("CategoryBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string CategoryBusiness {
            get {
                return ResourceManager.GetString("CategoryBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity.
        /// </summary>
        public static string CategoryCharity {
            get {
                return ResourceManager.GetString("CategoryCharity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        public static string CategoryClothing {
            get {
                return ResourceManager.GetString("CategoryClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string CategoryDeposit {
            get {
                return ResourceManager.GetString("CategoryDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string CategoryEntertainment {
            get {
                return ResourceManager.GetString("CategoryEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string CategoryFood {
            get {
                return ResourceManager.GetString("CategoryFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string CategoryHealth {
            get {
                return ResourceManager.GetString("CategoryHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string CategoryHome {
            get {
                return ResourceManager.GetString("CategoryHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string CategoryMiscellaneous {
            get {
                return ResourceManager.GetString("CategoryMiscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category name.
        /// </summary>
        public static string CategoryNameLabel {
            get {
                return ResourceManager.GetString("CategoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string CategoryUtilities {
            get {
                return ResourceManager.GetString("CategoryUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        public static string CategoryVacation {
            get {
                return ResourceManager.GetString("CategoryVacation", resourceCulture);
            }
        }
    }
}
