//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shane.Church.StirlingMoney.Data.Sync
{
    public partial class Account : Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageOfflineEntity {
        
        private System.Guid _AccountId;
        
        private string _AccountName;
        
        private double _InitialBalance;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Guid AccountId {
            get {
                return _AccountId;
            }
            set {
                base.OnPropertyChanging("AccountId");
                _AccountId = value;
                base.OnPropertyChanged("AccountId");
            }
        }
        
        public string AccountName {
            get {
                return _AccountName;
            }
            set {
                base.OnPropertyChanging("AccountName");
                _AccountName = value;
                base.OnPropertyChanged("AccountName");
            }
        }
        
        public double InitialBalance {
            get {
                return _InitialBalance;
            }
            set {
                base.OnPropertyChanging("InitialBalance");
                _InitialBalance = value;
                base.OnPropertyChanged("InitialBalance");
            }
        }
    }
    
    public partial class Category : Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageOfflineEntity {
        
        private System.Guid _CategoryId;
        
        private string _CategoryName;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Guid CategoryId {
            get {
                return _CategoryId;
            }
            set {
                base.OnPropertyChanging("CategoryId");
                _CategoryId = value;
                base.OnPropertyChanged("CategoryId");
            }
        }
        
        public string CategoryName {
            get {
                return _CategoryName;
            }
            set {
                base.OnPropertyChanging("CategoryName");
                _CategoryName = value;
                base.OnPropertyChanged("CategoryName");
            }
        }
    }
    
    public partial class Transaction : Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageOfflineEntity {
        
        private System.Guid @__accountId;
        
        private System.Guid _TransactionId;
        
        private System.DateTime _TransactionDate;
        
        private double _Amount;
        
        private string _Location;
        
        private string _Note;
        
        private bool _Posted;
        
        private System.Nullable<long> _CheckNumber;
        
        private System.Nullable<System.Guid> _CategoryId;
        
        public System.Guid _accountId {
            get {
                return @__accountId;
            }
            set {
                base.OnPropertyChanging("_accountId");
                @__accountId = value;
                base.OnPropertyChanged("_accountId");
            }
        }
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Guid TransactionId {
            get {
                return _TransactionId;
            }
            set {
                base.OnPropertyChanging("TransactionId");
                _TransactionId = value;
                base.OnPropertyChanged("TransactionId");
            }
        }
        
        public System.DateTime TransactionDate {
            get {
                return _TransactionDate;
            }
            set {
                base.OnPropertyChanging("TransactionDate");
                _TransactionDate = value;
                base.OnPropertyChanged("TransactionDate");
            }
        }
        
        public double Amount {
            get {
                return _Amount;
            }
            set {
                base.OnPropertyChanging("Amount");
                _Amount = value;
                base.OnPropertyChanged("Amount");
            }
        }
        
        public string Location {
            get {
                return _Location;
            }
            set {
                base.OnPropertyChanging("Location");
                _Location = value;
                base.OnPropertyChanged("Location");
            }
        }
        
        public string Note {
            get {
                return _Note;
            }
            set {
                base.OnPropertyChanging("Note");
                _Note = value;
                base.OnPropertyChanged("Note");
            }
        }
        
        public bool Posted {
            get {
                return _Posted;
            }
            set {
                base.OnPropertyChanging("Posted");
                _Posted = value;
                base.OnPropertyChanged("Posted");
            }
        }
        
        public System.Nullable<long> CheckNumber {
            get {
                return _CheckNumber;
            }
            set {
                base.OnPropertyChanging("CheckNumber");
                _CheckNumber = value;
                base.OnPropertyChanged("CheckNumber");
            }
        }
        
        public System.Nullable<System.Guid> CategoryId {
            get {
                return _CategoryId;
            }
            set {
                base.OnPropertyChanging("CategoryId");
                _CategoryId = value;
                base.OnPropertyChanged("CategoryId");
            }
        }
    }
    
    public partial class Budget : Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageOfflineEntity {
        
        private System.Guid _BudgetId;
        
        private string _BudgetName;
        
        private double _BudgetAmount;
        
        private System.Nullable<System.Guid> _CategoryId;
        
        private long _BudgetPeriod;
        
        private System.DateTime _StartDate;
        
        private System.Nullable<System.DateTime> _EndDate;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Guid BudgetId {
            get {
                return _BudgetId;
            }
            set {
                base.OnPropertyChanging("BudgetId");
                _BudgetId = value;
                base.OnPropertyChanged("BudgetId");
            }
        }
        
        public string BudgetName {
            get {
                return _BudgetName;
            }
            set {
                base.OnPropertyChanging("BudgetName");
                _BudgetName = value;
                base.OnPropertyChanged("BudgetName");
            }
        }
        
        public double BudgetAmount {
            get {
                return _BudgetAmount;
            }
            set {
                base.OnPropertyChanging("BudgetAmount");
                _BudgetAmount = value;
                base.OnPropertyChanged("BudgetAmount");
            }
        }
        
        public System.Nullable<System.Guid> CategoryId {
            get {
                return _CategoryId;
            }
            set {
                base.OnPropertyChanging("CategoryId");
                _CategoryId = value;
                base.OnPropertyChanged("CategoryId");
            }
        }
        
        public long BudgetPeriod {
            get {
                return _BudgetPeriod;
            }
            set {
                base.OnPropertyChanging("BudgetPeriod");
                _BudgetPeriod = value;
                base.OnPropertyChanged("BudgetPeriod");
            }
        }
        
        public System.DateTime StartDate {
            get {
                return _StartDate;
            }
            set {
                base.OnPropertyChanging("StartDate");
                _StartDate = value;
                base.OnPropertyChanged("StartDate");
            }
        }
        
        public System.Nullable<System.DateTime> EndDate {
            get {
                return _EndDate;
            }
            set {
                base.OnPropertyChanging("EndDate");
                _EndDate = value;
                base.OnPropertyChanged("EndDate");
            }
        }
    }
    
    public partial class Goal : Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageOfflineEntity {
        
        private System.Guid @__accountId;
        
        private System.Guid _GoalId;
        
        private string _GoalName;
        
        private double _Amount;

		private double _InitialBalance;
        
        private System.DateTime _TargetDate;
        
        public System.Guid _accountId {
            get {
                return @__accountId;
            }
            set {
                base.OnPropertyChanging("_accountId");
                @__accountId = value;
                base.OnPropertyChanged("_accountId");
            }
        }
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Guid GoalId {
            get {
                return _GoalId;
            }
            set {
                base.OnPropertyChanging("GoalId");
                _GoalId = value;
                base.OnPropertyChanged("GoalId");
            }
        }
        
        public string GoalName {
            get {
                return _GoalName;
            }
            set {
                base.OnPropertyChanging("GoalName");
                _GoalName = value;
                base.OnPropertyChanged("GoalName");
            }
        }
        
        public double Amount {
            get {
                return _Amount;
            }
            set {
                base.OnPropertyChanging("Amount");
                _Amount = value;
                base.OnPropertyChanged("Amount");
            }
        }

		public double InitialBalance
		{
			get
			{
				return _InitialBalance;
			}
			set
			{
				base.OnPropertyChanging("InitialBalance");
				_InitialBalance = value;
				base.OnPropertyChanged("InitialBalance");
			}
		}        

        public System.DateTime TargetDate {
            get {
                return _TargetDate;
            }
            set {
                base.OnPropertyChanging("TargetDate");
                _TargetDate = value;
                base.OnPropertyChanged("TargetDate");
            }
        }
    }
}
